### ISSUE TITLE
postinstall error on Windows

### ISSUE THREAD

**Issue by ilyasdx91** [richardeschloss/nuxt-highcharts#3]
cannot install dependencies on Windows because of "postinstall": " rm -rf node_modules/.cache/ .nuxt/".
solved this problem by executing npm install via Git Bash.
please fix this, to avoid future misunderstandings.
thank you

**Comment by richardeschloss** [comment]
Hi thanks for catching the bug. It's actually really easy to fix. Do you want to submit the PR? All that's needed is to remove the postinstall script from package.json. I can do it, but I figure I can give you the chance to be a contributor since you caught the bug.

The fix is just to delete this line: https://github.com/richardeschloss/nuxt-highcharts/blob/ec2cd7618d1ea152d0333d88a09f03063cd422a1/package.json#L31
