### ISSUE TITLE
Chart update does not work when changing the options

### ISSUE THREAD

**Issue by mostafa-rahmani** [richardeschloss/nuxt-highcharts#32]
### Version
nuxt-highcharts: 1.0.7
nuxt: 2.14.6

### Nuxt configuration
 mode: universal

### Nuxt configuration for nuxt-highchart
```
module.exports = {
...
  plugins: [
      new webpack.IgnorePlugin({
              resourceRegExp: /\@highcharts\/map\-collection/,
            }),
            new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
          ]
      ]
...
}
```
### Steps to reproduce

 <highchart
      class="chart"
      :redraw="true"
      :options="transactionChart"
      :update="['options.series']"
    />

### What is Expected?
When I update the transactionChart value which is the options variable, then the chart must redraw

### What is actually happening?
When I update the options the charts does not change or redraw

**Comment by richardeschloss** [comment]
More information is needed. How are you implementing the `<highchart />` component and where in the options is your `transactionChart` value? I'm not aware of that property on the options.

**Comment by richardeschloss** [comment]
Tests on this pass, here is the specific test that passes:

https://github.com/richardeschloss/nuxt-highcharts/blob/b2ec0883a78300d7e816896a3dacf4d0ea377f1c/test/unit/components.js#L155

The working demo is also here https://nuxt-highcharts.netlify.app/chart . When the options change, the chart updates. It sounds like the issue is rooted in understanding observability fundamentals in Vue.
