### ISSUE TITLE
Nuxt 3 Beta released. Will there be support?

### ISSUE THREAD

**Issue by zavodptica** [richardeschloss/nuxt-highcharts#38]
Hi! Now nuxt-highcharts does not work with nuxt3. Will there be nuxt3 support?

**Comment by richardeschloss** [comment]
Update: as of this writing, nuxt3-beta is not quite ready it seems. The architecture has changed quite a bit, causing existing plugin features to not work. The following does not work in the plugin any more: (as would apply to any v2 plugins)

- The ERB templates no longer compile the plugin options
- The Nuxt API for modules changed, requiring different filename scheme than before.
- Vue.component is unavailable in the plugin, so being able to easily define the highchart components is not possible in the plugin.
- The feature for scanning the node-modules/highcharts directory for its modules is now broken because require.context won't work (require not allowed in ESM)
- Likewise, a bunch of old require statements had to be replaced with imports (this part was pretty straightforward)
- bootstrap-vue/nuxt fails to add the components used for the demo. 
- The <component :is="..." /> is not working, and neither is the dynamic routing for pages.

So, this tells me nuxt3 still has quite a few issues to work out before upgrading the module.

**Comment by pixelspark** [comment]
Awesome. I tried this, but ran into the following:

````
 ERROR  Cannot start nuxt:  Cannot find module '/XXXXX/node_modules/nuxt-highcharts/highcharts/module.js'. Please verify that the package.json has a valid "main" entry
````

The package.json's "main" entry:

````
 "main": "highcharts/module.js",
````

The package does not contain this file, it does have "lib/module.js", so perhaps "main" needs to be set to "lib/module.js"? Trying this makes Nuxt start, but gives me the following error on the browser side:

````
components.js:1 
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/highcharts/highcharts.js?v=36ef820a' does not provide an export named 'default'
````

**Comment by richardeschloss** [comment]
Hi thanks for catching that. Yes, I just pushed the update. Please try again :)

**Comment by richardeschloss** [comment]
Ok, I know what's going on. I'm working on this right now.

**Comment by richardeschloss** [comment]
Nuxt3 support working and here 
> npm i nuxt-highcharts@next

**Comment by richardeschloss** [comment]
Update: 01-27-2022: just pushed with extended type support. This should make it much easier now to use the Intellisense :muscle: .

For example: to use on a computed prop "chartOpts":
```js
computed: {
  /* @returns {import('highcharts/highcharts').Options} */
  chartOpts() {
    return {
      // typing you'll get the suggestions
    }
  }
}
