### ISSUE TITLE
Example of using an Indicator - e.g. Candlesticks with EMA

### ISSUE THREAD

**Issue by JamesPooleFX** [richardeschloss/nuxt-highcharts#43]
Hi @richardeschloss - would you be kind enough to give an example on how to include an Indicator (e.g. ema) in a Highstocks chart? i.e. perhaps a similar [example](https://github.com/richardeschloss/nuxt-highcharts/blob/master/components/charts/StockChart.vue) for a scenario like [this](https://codepen.io/mushigh/pen/mdrwMJZ)?

Thanks!

**Comment by richardeschloss** [comment]
Hi, here's a working example for Nuxt 2. Basically, import the indicators library and use it: (it's important to use the correct highcharts constructor for things to work)
https://stackblitz.com/edit/nuxt-starter-cvmkva?file=components/StockChart.vue

Integrating this directly into the nuxt-highcharts component factory is planned for the Nuxt3 compatible module (since Nuxt3 provides the much faster dev and user experience). That working branch is here:
https://github.com/richardeschloss/nuxt-highcharts/tree/feat/v3-indicators
https://github.com/richardeschloss/nuxt-highcharts/blob/83c6566262dfc4c58945c37e9524364143bdcc63/lib/components.js#L34

**Comment by richardeschloss** [comment]
I just pushed feat/v3 with this support merged in. Using it with Nuxt3 is even easier...in that one just use it without any extra coding or imports.

> npm i nuxt-highcharts@next # requires Nuxt3 

Then just use highstock component:
```html
<highstock :options="chartOpts" /> 
```
https://github.com/richardeschloss/nuxt-highcharts/blob/feat/v3/components/charts/StockChart.vue  (working example for Nuxt3 version)

**Comment by JamesPooleFX** [comment]
Thanks @richardeschloss - much appreciated!
