### ISSUE TITLE
Performance: Load only needed charts to the bundle

### ISSUE THREAD

**Issue by koblents** [richardeschloss/nuxt-highcharts#52]
Hi! When I analyze my bundle, I see all chart types in it, while I am using only few. 
How can I setup module to only load chart that I use?

Thanks

**Comment by richardeschloss** [comment]
What version are you using? The module for Nuxt 2.x or Nuxt 3.x?

**Comment by koblents** [comment]
Nuxt 2.15.8

**Comment by koblents** [comment]
Any thoughts?

**Comment by richardeschloss** [comment]
I was hoping to get to this tonight. I currently have had other obligations. It's also been a while since I've worked on the Nuxt 2.x version of this library, so I'll have to shift back that. I'm guessing the static `import Highcharts from 'highcharts'` is the culprit. Highcharts >= 9.2 now has the [ES6 support](https://www.highcharts.com/docs/getting-started/installation-with-esm) and we may wish to use that, so we only import the parts we want. (a lot of the jsfiddle demos are based on older versions of Highcharts)

The static import could probably change to a dynamic import, so it's only loaded when needed.

**Comment by koblents** [comment]
Ok, please update me if you will found some solution. With direct import there is another issue - of ssr, since this library should be loaded only on client side. For now if I create just nuxt pluging based on vue-highcharts module, it looks like this

`import Vue from 'vue'
import HighchartsVue from 'highcharts-vue'
import Highcharts from 'highcharts'
import HighchartsMore from 'highcharts/highcharts-more'
import treemapInit from "highcharts/modules/treemap";
import heatmapInit from "highcharts/modules/heatmap";
import solidGaugeInit from "highcharts/modules/solid-gauge";

Highcharts.setOptions({ accessibility: { enabled: false } })
HighchartsMore(Highcharts);
treemapInit(Highcharts);
heatmapInit(Highcharts);
solidGaugeInit(Highcharts);

Vue.use(HighchartsVue)`

But the problem that I want to use it local, not as global plugin, at least treemapInit and heatmapInit - but don't know how to load them only for client side.

**Comment by richardeschloss** [comment]
Ok. Most likely I will be working on the support for Nuxt3 version since that's ESM-based and should make it easier to separate out parts of the code. (For your question on client-side only, I relocated that to discussions #53, to keep the scope of this issue focused).

**Comment by richardeschloss** [comment]
For now, to achieve smaller builds, I would recommend temporarily disabling nuxt-highcharts module, and consider cherry picking exactly the es-modules you need: 

```js
<template>
  <div />
</template>

<script>
const imports = {
  LineSeries: () => import('highcharts/es-modules/Series/Line/LineSeries.js') // Needed so we can dynamically import with variable expressions below
}

export default {
  data () {
    return {
      chart: {},
      opts: {
        accessibility: { enabled: false },
        series: [{ data: [1, 2, 3] }]
      },
      deps: ['LineSeries']
    }
  },
  async mounted () {
    const Chart = (await import('highcharts/es-modules/Core/Chart/Chart.js')).default // Always required.
    await Promise.all(this.deps.map(d => imports[d]()))
    this.chart = new Chart(this.$el, this.opts)
  }
}
</script>

```
It also seems that in some ways, that'd be more appropriate to import directly their ES modules
Here, the Core chart module is lazy loaded, and then only the modules it needs are loaded. It seems like my library would need a major overhaul to support all the new ES-modules they provide, and I don't know right now if it's worth the effort. Highcharts docs also [warn](https://www.highcharts.com/docs/getting-started/installation-with-esm#including-a-product-package-es6-module) "Please note that this results in a decreased download size but in an increased delay caused by the amount of (small) files to load. This approach is therefore not recommended for production."

**Comment by richardeschloss** [comment]
I was curious to see the actual bundle size. When isolating to just the above snippet, I end up with this:

```
start Writing server bundle...                                  nitro 10:42:21
✔ Server built                                                  nitro 10:42:24
  ├─ .output/server/package.json (325 B) (188 B gzip)
  ├─ .output/server/index.mjs (458 B) (255 B gzip)
  ├─ .output/server/chunks/SeriesRegistry.mjs.map (35.6 kB) (5.31 kB gzip)
  ├─ .output/server/chunks/SeriesRegistry.mjs (55.4 kB) (15.5 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (56.5 kB) (4.33 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (16.6 kB) (5.32 kB gzip)
  ├─ .output/server/chunks/LineSeries.mjs.map (7.97 kB) (1.61 kB gzip)
  ├─ .output/server/chunks/LineSeries.mjs (10.6 kB) (3.01 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (1.92 MB) (91.1 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (430 kB) (98.5 kB gzip)
  ├─ .output/server/chunks/Chart.mjs.map (418 kB) (55.6 kB gzip)
  ├─ .output/server/chunks/Chart.mjs (680 kB) (152 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (169 kB) (24.3 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (145 kB) (36.3 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (1.04 kB) (369 B gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (1.32 kB) (395 B gzip)
Σ Total size: 5.28 MB (815 kB gzip)
```
(The Core library is about 2 MB)


Comparing this to the current repo's setup:

```
start Writing server bundle...                                  nitro 10:46:55
✔ Server built                                                  nitro 10:46:56
  ├─ .output/server/package.json (325 B) (188 B gzip)
  ├─ .output/server/index.mjs (458 B) (255 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (60.5 kB) (4.42 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (38 kB) (10.3 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (1.92 MB) (91.1 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (430 kB) (98.5 kB gzip)
  ├─ .output/server/chunks/app/server.mjs.map (1.28 MB) (43.5 kB gzip)
  ├─ .output/server/chunks/app/server.mjs (1.43 MB) (165 kB gzip)
  ├─ .output/server/chunks/app/client.manifest.mjs.map (10.3 kB) (1.03 kB gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (13.5 kB) (2.36 kB gzip)
Σ Total size: 7.92 MB (1.18 MB gzip)
```

Which is about 2.63 MB larger, which isn't too bad considering its versatility.
